# Generated by Django 3.2.8 on 2021-10-15 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Deceased',
            fields=[
                ('deceasedid', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('firstname', models.CharField(max_length=50)),
                ('Middlename', models.CharField(blank=True, max_length=50, null=True)),
                ('lastname', models.CharField(max_length=50)),
                ('Date_of_Birth', models.DateField()),
                ('Date_of_death', models.DateField()),
                ('Life_Description', models.TextField()),
                ('funeral_arrangements', models.TextField(default='het')),
                ('photo', models.ImageField(upload_to='')),
                ('condolences', models.CharField(default='RIP', max_length=250)),
                ('no_condolence', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Deceased',
            },
        ),
        migrations.CreateModel(
            name='DeceasedGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(blank=True, upload_to='images/')),
                ('deceasedid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.deceased')),
            ],
        ),
        migrations.AddField(
            model_name='deceased',
            name='imageGallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='index.deceasedgallery'),
        ),
        migrations.CreateModel(
            name='CondolenceNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('deceasedid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='index.deceased')),
            ],
            options={
                'verbose_name_plural': 'Condolence Notes',
            },
        ),
    ]
