# Generated by Django 3.2.8 on 2021-10-15 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20211015_1431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='condolencenotes',
            old_name='name',
            new_name='condoled_by',
        ),
    ]
