# Generated by Django 3.2.8 on 2021-10-15 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_rename_name_condolencenotes_condoled_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='deceased',
            name='no_condolence',
            field=models.IntegerField(default=0),
        ),
    ]
