# Generated by Django 3.2.8 on 2021-10-15 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_deceased_no_condolence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condolencenotes',
            name='deceasedid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='condolences', to='index.deceased'),
        ),
    ]
