# Generated by Django 3.2.8 on 2021-10-19 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_alter_condolencenotes_deceasedid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deceasedgallery',
            name='deceasedid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_gallery', to='index.deceased'),
        ),
    ]
